#!/usr/bin/env python

from exifread import process_file
import sys

if len(sys.argv) != 2:
  print("Pass filename to check (jpg, nef)")
  sys.exit(1)

with open(sys.argv[1], 'rb') as f:
    data = process_file(f)
print(data.get("MakerNote TotalShutterReleases", "not found--make sure to use file straight from camera"))
